# Generated by Django 5.0.6 on 2024-08-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seetha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carloandocument',
            old_name='loan_type',
            new_name='loan',
        ),
        migrations.RemoveField(
            model_name='carloan',
            name='required_loan_amount',
        ),
        migrations.RemoveField(
            model_name='carloandocument',
            name='downpayment_amount',
        ),
        migrations.RemoveField(
            model_name='carloandocument',
            name='other_document_3',
        ),
        migrations.RemoveField(
            model_name='carloandocument',
            name='other_document_4',
        ),
        migrations.RemoveField(
            model_name='carloandocument',
            name='quotation_value_on_ex_showroom',
        ),
        migrations.RemoveField(
            model_name='carloandocument',
            name='showroom_quotation',
        ),
        migrations.AddField(
            model_name='carloan',
            name='company_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public'), ('government', 'Government'), ('self_employed', 'Self Employed'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='carloan',
            name='existing_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carloan',
            name='job_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carloan',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carloan',
            name='required_loan_amount1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='carloan',
            name='required_loan_amount2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carloan',
            name='showroom_quotation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carloan',
            name='total_job_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carloan',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='application_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='business_address_pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='business_establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company'), ('LLP', 'Limited Liability Partnership'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='car_loan_type',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='downpayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='gst_certificate',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='income_source',
            field=models.CharField(choices=[('Job', 'Job'), ('Business', 'Business')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='net_income_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='own_house',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='quotation_valaue_on_ex_showroom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='ref_1_person_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='ref_1_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='ref_2_person_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='ref_2_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='turnover_in_lakhs_per_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carloandocument',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='carloandocument',
            name='current_address_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
